// actions/types.js
export const ADD_SALE = 'ADD_SALE';
export const DELETE_SALE = 'DELETE_SALE';
export const UPDATE_SALE = 'UPDATE_SALE';
export const SELECT_SALE = 'SELECT_SALE';

export const ADD_INVENTORY_ITEM = 'ADD_INVENTORY_ITEM';
export const DELETE_INVENTORY_ITEM = 'DELETE_INVENTORY_ITEM';
export const UPDATE_INVENTORY_ITEM = 'UPDATE_INVENTORY_ITEM';
export const SELECT_INVENTORY_ITEM = 'SELECT_INVENTORY_ITEM';

export const ADD_STOCK = 'ADD_STOCK';
export const DELETE_STOCK = 'DELETE_STOCK';
export const UPDATE_STOCK = 'UPDATE_STOCK';
export const SELECT_STOCK = 'SELECT_STOCK';